/**
 * Generate embed.generated.ts from dist/ directory
 *
 * This script scans the dist/ directory and generates a TypeScript file
 * that imports all files using Bun's { type: "file" } syntax for embedding
 * into compiled binaries.
 */

import { readdir } from "node:fs/promises";
import { extname, join, relative } from "node:path";

const DIST_DIR = join(import.meta.dir, "..", "dist");
const OUTPUT_FILE = join(import.meta.dir, "..", "embed.generated.ts");

// MIME type mapping
const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".map": "application/json",
};

function getMimeType(filePath: string): string {
  const ext = extname(filePath).toLowerCase();
  return MIME_TYPES[ext] || "application/octet-stream";
}

function sanitizeVarName(path: string): string {
  // Convert path to valid variable name
  return path
    .replace(/[^a-zA-Z0-9]/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_");
}

async function getAllFiles(dir: string): Promise<string[]> {
  const files: string[] = [];

  async function scan(currentDir: string) {
    const entries = await readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = join(currentDir, entry.name);
      if (entry.isDirectory()) {
        await scan(fullPath);
      } else if (entry.isFile()) {
        files.push(fullPath);
      }
    }
  }

  await scan(dir);
  return files;
}

async function main() {
  console.log("Scanning dist/ directory...");

  const files = await getAllFiles(DIST_DIR);
  if (files.length === 0) {
    console.error("No files found in dist/. Run 'bun run build' first.");
    process.exit(1);
  }

  const imports: string[] = [];
  const assets: string[] = [];

  for (const fullPath of files) {
    const relativePath = relative(DIST_DIR, fullPath);
    const varName = sanitizeVarName(relativePath);
    const urlPath = `/${relativePath}`;
    const mime = getMimeType(fullPath);

    // Generate import statement
    imports.push(`import ${varName} from "./dist/${relativePath}" with { type: "file" };`);

    // Generate asset entry
    assets.push(`  "${urlPath}": { path: ${varName}, mime: "${mime}" },`);

    // Add root path mapping for index.html
    if (relativePath === "index.html") {
      assets.push(`  "/": { path: ${varName}, mime: "${mime}" },`);
    }
  }

  const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-embed.ts

${imports.join("\n")}

export interface EmbeddedAsset {
  path: string;
  mime: string;
}

export const embeddedAssets: Record<string, EmbeddedAsset> = {
${assets.join("\n")}
};
`;

  await Bun.write(OUTPUT_FILE, output);
  console.log(`Generated embed.generated.ts with ${files.length} files`);
}

main();
